Repository DungeonTalk/dungeontalk-backend, pull requests merged in 2025-08, with the labels that each got.

#9 [Config] Project Global 처리 : RsData + Exception + Spring Security (#7)
  build.gradle
  src/main/java/org/com/dungeontalk/domain/auth/entity/Auth.java
  src/main/java/org/com/dungeontalk/domain/auth/entity/AuthId.java
  src/main/java/org/com/dungeontalk/domain/auth/repository/AuthRepository.java
  src/main/java/org/com/dungeontalk/domain/member/controller/MemberController.java
  src/main/java/org/com/dungeontalk/domain/member/dto/request/RegisterRequest.java
  src/main/java/org/com/dungeontalk/domain/member/dto/response/RegisterResponse.java
  src/main/java/org/com/dungeontalk/domain/member/entity/Member.java
  src/main/java/org/com/dungeontalk/domain/member/repository/MemberRepository.java
  src/main/java/org/com/dungeontalk/domain/member/service/MemberService.java
  src/main/java/org/com/dungeontalk/global/config/CorsConfig.java
  src/main/java/org/com/dungeontalk/global/config/SecurityConfig.java
  src/main/java/org/com/dungeontalk/global/config/ValkeyConfig.java
  src/main/java/org/com/dungeontalk/global/exception/ErrorCode.java
  src/main/java/org/com/dungeontalk/global/exception/GlobalExceptionHandler.java
  src/main/java/org/com/dungeontalk/global/exception/Guide.md
  src/main/java/org/com/dungeontalk/global/exception/customException/MemberException.java
  src/main/java/org/com/dungeontalk/global/rsData/Empty.java
  src/main/java/org/com/dungeontalk/global/rsData/Guide.md
  src/main/java/org/com/dungeontalk/global/rsData/ResponseStatus.java
  src/main/java/org/com/dungeontalk/global/rsData/RsData.java
  src/main/java/org/com/dungeontalk/global/security/CustomUserDetails.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationFilter.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationToken.java
  src/main/java/org/com/dungeontalk/global/security/JwtService.java
Labels: ⚙️ Setting

#10 feat(Auth) 로그인 Valkey 이슈 해결 및 기초 인증&인가 시스템 구축
  build.gradle
  src/main/java/org/com/dungeontalk/DungeontalkApplication.java
  src/main/java/org/com/dungeontalk/domain/auth/controller/AuthController.java
  src/main/java/org/com/dungeontalk/domain/auth/controller/ValkeyController.java
  src/main/java/org/com/dungeontalk/domain/auth/dto/request/AuthLoginRequest.java
  src/main/java/org/com/dungeontalk/domain/auth/dto/response/AuthLoginResponse.java
  src/main/java/org/com/dungeontalk/domain/auth/entity/Auth.java
  src/main/java/org/com/dungeontalk/domain/auth/repository/AuthRepository.java
  src/main/java/org/com/dungeontalk/domain/auth/service/AuthService.java
  src/main/java/org/com/dungeontalk/domain/auth/service/ValkeyService.java
  src/main/java/org/com/dungeontalk/domain/member/controller/MemberController.java
  src/main/java/org/com/dungeontalk/domain/member/dto/request/RegisterRequest.java
  src/main/java/org/com/dungeontalk/domain/member/entity/Member.java
  src/main/java/org/com/dungeontalk/domain/member/repository/MemberRepository.java
  src/main/java/org/com/dungeontalk/domain/member/service/MemberService.java
  src/main/java/org/com/dungeontalk/global/common/entity/BaseEntity.java
  src/main/java/org/com/dungeontalk/global/config/SecurityConfig.java
  src/main/java/org/com/dungeontalk/global/config/ValkeyConfig.java
  src/main/java/org/com/dungeontalk/global/exception/ErrorCode.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationFilter.java
  src/main/java/org/com/dungeontalk/global/security/JwtService.java
  src/main/java/org/com/dungeontalk/global/util/UuidV7Creator.java
Labels: ✨ Feature

#12 [Feature] 기능 개발 - WebSocket 활용한 멀티 채팅 기능 개발 #2
  build.gradle
  src/main/java/org/com/dungeontalk/domain/chat/common/ChatMode.java
  src/main/java/org/com/dungeontalk/domain/chat/common/ChatRoomType.java
  src/main/java/org/com/dungeontalk/domain/chat/common/MessageType.java
  src/main/java/org/com/dungeontalk/domain/chat/controller/ChatRoomController.java
  src/main/java/org/com/dungeontalk/domain/chat/controller/ChatStompController.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatMessageDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatRoomDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ConnectedCountMessageDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/request/ChatMessageSendRequestDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/request/ChatRoomCreateRequestDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/org/com/dungeontalk/domain/chat/entity/ChatMessage.java
  src/main/java/org/com/dungeontalk/domain/chat/entity/ChatRoom.java
  src/main/java/org/com/dungeontalk/domain/chat/repository/ChatMessageRepository.java
  src/main/java/org/com/dungeontalk/domain/chat/repository/ChatRoomRepository.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatMessageService.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatRoomService.java
  src/main/java/org/com/dungeontalk/domain/member/repository/MemberRepository.java
  src/main/java/org/com/dungeontalk/global/config/SecurityConfig.java
  src/main/java/org/com/dungeontalk/global/config/ValkeyConfig.java
  src/main/java/org/com/dungeontalk/global/config/WebSocketConfig.java
  src/main/java/org/com/dungeontalk/global/redis/ChatRoomMemberManager.java
  src/main/java/org/com/dungeontalk/global/redis/RedisPublisher.java
  src/main/java/org/com/dungeontalk/global/redis/RedisSubscriber.java
  src/main/java/org/com/dungeontalk/global/security/JwtService.java
  src/main/java/org/com/dungeontalk/global/websocket/JwtHandshakeInterceptor.java
Labels: ✨ Feature

#14 Setting - Swagger API 적용 및 Application.properties 분기 및 환경 변수 처리 (#11)
  .gitignore
  build.gradle
  src/main/java/org/com/dungeontalk/global/config/Swagger/Guide.md
  src/main/java/org/com/dungeontalk/global/config/Swagger/SwaggerConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: ⚙️ Setting

#22 [Refactor] 리팩토링 AI 채팅 모듈의 대규모 리팩토링을 통해 코드 품질, 성능, 유지보수성을 대폭 개선
  docs/aichat/package-structure-guide.md
  docs/aichat/refactoring-guide.md
  src/main/java/org/com/dungeontalk/domain/aichat/common/AiChatConstants.java
  src/main/java/org/com/dungeontalk/domain/aichat/config/AiChatConfigHelper.java
  src/main/java/org/com/dungeontalk/domain/aichat/config/AiChatProperties.java
  src/main/java/org/com/dungeontalk/domain/aichat/config/AiGameMessageIndexConfig.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiChatStompController.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiGameRoomController.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiResponseController.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/SessionDataDto.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiErrorRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGenerateRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiMessageSaveRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiResponseRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameMessageResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameRoomResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/ProcessingStatusResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoom.java
  src/main/java/org/com/dungeontalk/domain/aichat/repository/AiGameMessageRepository.java
  src/main/java/org/com/dungeontalk/domain/aichat/repository/AiGameRoomRepository.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameRoomService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameStateService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiResponseService.java
  src/main/java/org/com/dungeontalk/domain/aichat/util/AiChatErrorHandler.java
  src/main/java/org/com/dungeontalk/domain/aichat/util/AiChatLogUtils.java
  src/main/java/org/com/dungeontalk/domain/aichat/util/AiGameValidator.java
  src/main/java/org/com/dungeontalk/global/exception/ErrorCode.java
  src/main/java/org/com/dungeontalk/global/exception/customException/AiChatException.java
  src/main/resources/application-dev.properties
  src/main/resources/mongodb/indexes/ai-game-message-indexes.js
  src/main/resources/static/ai-chat-test.html
Labels: 🔧 Refactor

#25 [Feature] 랜덤 매칭 시스템 구현 - 실시간 3인 파티 매칭 및 자동 게임방 생성
  .claude/settings.local.json
  docs/matching/README.md
  docs/matching/redis-queue-design.md
  src/main/java/org/com/dungeontalk/domain/aichat/config/AiGameMessageIndexConfig.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiChatStompController.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiResponseController.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoom.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameStateService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiResponseService.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatRoomDto.java
  src/main/java/org/com/dungeontalk/domain/matching/common/MatchingConstants.java
  src/main/java/org/com/dungeontalk/domain/matching/common/MatchingStatus.java
  src/main/java/org/com/dungeontalk/domain/matching/common/WorldType.java
  src/main/java/org/com/dungeontalk/domain/matching/config/MatchingAsyncConfig.java
  src/main/java/org/com/dungeontalk/domain/matching/config/MatchingProperties.java
  src/main/java/org/com/dungeontalk/domain/matching/config/MatchingStartupConfig.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingController.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingWebSocketController.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/request/MatchingCancelRequest.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/request/MatchingJoinRequest.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/MatchingCompleteResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/MatchingStatusResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/QueueStatsResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/WorldQueueInfo.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/websocket/MatchingWebSocketMessage.java
  src/main/java/org/com/dungeontalk/domain/matching/exception/MatchingException.java
  src/main/java/org/com/dungeontalk/domain/matching/factory/MatchingRoomFactory.java
  src/main/java/org/com/dungeontalk/domain/matching/factory/RoomCreationContext.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingQueueManager.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingService.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingWebSocketMessageFactory.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingWebSocketService.java
  src/main/java/org/com/dungeontalk/domain/matching/util/MatchingTimeCalculator.java
  src/main/java/org/com/dungeontalk/global/config/HttpClientConfig.java
  src/main/java/org/com/dungeontalk/global/config/ValkeyConfig.java
  src/main/java/org/com/dungeontalk/global/exception/ErrorCode.java
  src/main/java/org/com/dungeontalk/global/redis/AiChatRedisSubscriber.java
  src/main/java/org/com/dungeontalk/global/redis/RedisPublisher.java
  src/main/resources/application-dev.properties
  src/main/resources/static/ai-chat-simple-test.html
  src/main/resources/static/ai-chat-test.html
  src/main/resources/static/dungeon-game.html
  src/main/resources/static/login-test.html
Labels: ✨ Feature

#30 [Feature] 기능 개발 - 채팅방 인원 수 확인 + 실시간 입장/퇴장/재입장/재퇴장을 실시간 접속자 수에 반영 #26
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatRoomDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatRoomPresenceDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/MemberPresenceDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/PresenceBroadcastDto.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/request/ChatRoomCreateRequestDto.java
  src/main/java/org/com/dungeontalk/domain/chat/entity/ChatMessage.java
  src/main/java/org/com/dungeontalk/domain/chat/entity/ChatRoom.java
  src/main/java/org/com/dungeontalk/domain/chat/entity/ChatRoomMember.java
  src/main/java/org/com/dungeontalk/domain/chat/event/ChatPresenceEvent.java
  src/main/java/org/com/dungeontalk/domain/chat/listener/ChatPresenceSystemMessageListener.java
  src/main/java/org/com/dungeontalk/domain/chat/repository/ChatMessageRepository.java
  src/main/java/org/com/dungeontalk/domain/chat/repository/ChatRoomRepository.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatMessageService-guide.md
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatMessageService.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatRoomMemberService.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatRoomService.java
  src/main/java/org/com/dungeontalk/domain/chat/util/ChatRoomProperties.java
  src/main/java/org/com/dungeontalk/global/redis/ChatRoomMemberManager.java
  src/main/java/org/com/dungeontalk/global/redis/RedisPublisher.java
  src/main/java/org/com/dungeontalk/global/websocket/WebSocketDisconnectHandler.java
  src/main/resources/application-dev.properties
  src/main/resources/mongodb/indexes/ai-game-message-indexes.js
  src/main/resources/static/chat-ssr-test.html
  src/main/resources/static/login-chat-test.html
Labels: ✨ Feature

#44 [Refactor] 한국어 욕설 필터링 시스템을 전면 도입하여 건전한 채팅 환경을 구축
  build.gradle
  src/main/java/org/com/dungeontalk/domain/aichat/config/AiChatProperties.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiGameRoomController.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/AiGameMessageDto.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/AiGameRoomDto.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiErrorRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGameMessageSendRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGameRoomCreateRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGameRoomJoinRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGenerateRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiResponseRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameMessageResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameRoomResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameMessage.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoom.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameFlowService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameRoomService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameRoomServiceAdapter.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameStateService.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatMessageService.java
  src/main/java/org/com/dungeontalk/domain/matching/config/MatchingProperties.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingController.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/request/MatchingCancelRequest.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/request/MatchingJoinRequest.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/MatchingStatusResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingService.java
  src/main/java/org/com/dungeontalk/domain/room/controller/UnifiedRoomController.java
  src/main/java/org/com/dungeontalk/domain/room/dto/RoomMemberRequest.java
  src/main/java/org/com/dungeontalk/domain/room/dto/UnifiedRoomRequest.java
  src/main/java/org/com/dungeontalk/domain/room/dto/UnifiedRoomResponse.java
  src/main/java/org/com/dungeontalk/global/filter/ProfanityFilterService.java
  src/main/java/org/com/dungeontalk/global/filter/config/ProfanityFilterProperties.java
  src/main/java/org/com/dungeontalk/global/filter/dto/MessageValidationResult.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationFilter.java
  src/main/resources/application-dev.properties
  src/main/resources/profanity-words.txt
  src/main/resources/static/dungeon-game.html
Labels: ✨ Feature

#45 [Test] 테스트 - 채팅 서비스 테스트 코드 작성
  build.gradle
  docs/chatdir/ChatMessageService-guide.md
  docs/testdir/testguide.md
  src/main/java/org/com/dungeontalk/DungeontalkApplication.java
  src/main/java/org/com/dungeontalk/domain/chat/dto/ChatRoomDto.java
  src/main/java/org/com/dungeontalk/domain/chat/service/ChatRoomService.java
  src/main/java/org/com/dungeontalk/global/config/JpaAuditingConfig.java
  src/main/resources/application-test.properties
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatRoomMemberRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/service/ChatMessageServiceTest.java
  src/test/java/org/com/dungeontalk/domain/chat/service/ChatRoomMemberServiceTest.java
  src/test/java/org/com/dungeontalk/domain/chat/service/ChatRoomServiceTest.java
Labels: ✅ Test

#47 test(hotfix): 테스트 코드 컴파일 이슈 처리
  build.gradle
Labels: 🐞 Bugfix

#51 [Feature] 캐릭터 생성, 조회 및 종족별 스탯 계산 기능을 구현
  build.gradle
  src/main/java/org/com/dungeontalk/domain/gamecharacter/controller/GameCharacterController.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/dto/request/CreateCharacterRequest.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/dto/response/GameCharacterDetailResponse.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/dto/response/GameCharacterResponse.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/entity/GameCharacter.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/repository/GameCharacterRepository.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/service/GameCharacterService.java
  src/main/java/org/com/dungeontalk/domain/stat/controller/DataInitController.java
  src/main/java/org/com/dungeontalk/domain/stat/controller/StatController.java
  src/main/java/org/com/dungeontalk/domain/stat/dto/response/CalculatedStatsResponse.java
  src/main/java/org/com/dungeontalk/domain/stat/entity/RaceStats.java
  src/main/java/org/com/dungeontalk/domain/stat/repository/RaceStatsRepository.java
  src/main/java/org/com/dungeontalk/domain/stat/service/StatAggregateService.java
  src/main/java/org/com/dungeontalk/domain/stat/service/StatCalculatorService.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationFilter.java
  src/main/java/org/com/dungeontalk/global/security/JwtProvider.java
  src/main/resources/static/character-test.html
  src/main/resources/static/stat-calculator.html
Labels: ✨ Feature

#54 refactor(aichat): DTO 클래스 구조 개선 및 코드 정리
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiServiceRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/ContextMessage.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiServiceResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiApiService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameFlowService.java
Labels: 🔧 Refactor

#56 [CI/CD] 배포 작업 - railway 활용한 백엔드 프로젝트 CI/CD 테스트 진행
  .dockerignore
  Dockerfile
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: 🤖 CI/CD

#63 cicd: cicd 구축 위한 구성 파일 수정
  .dockerignore
  .gitignore
  Dockerfile
Labels: 🤖 CI/CD

#64 [TEST] AiServiceRequest, AiGameMessageRepository, AiGameMessageService 테스트 코드 추가
  src/main/java/org/com/dungeontalk/domain/aichat/dto/AiGameMessageDto.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/AiGameRoomDto.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameMessageResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiGameRoomResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameMessage.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoom.java
  src/main/java/org/com/dungeontalk/domain/aichat/repository/AiGameRoomRepository.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameRoomService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameStateService.java
  src/test/java/org/com/dungeontalk/domain/aichat/dto/request/AiServiceRequestTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/repository/AiGameMessageRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageServiceTest.java
  src/test/java/org/com/dungeontalk/domain/matching/dto/request/MatchingJoinRequestTest.java
  src/test/java/org/com/dungeontalk/domain/matching/service/MatchingQueueManagerTest.java
  src/test/java/org/com/dungeontalk/domain/matching/service/MatchingServiceTest.java
  src/test/java/org/com/dungeontalk/domain/room/service/RoomServiceFactoryTest.java
Labels: ✅ Test

#77 [Setting] 스웨거 토큰 환경 설정 추가
  src/main/java/org/com/dungeontalk/global/config/Swagger/SwaggerConfig.java
Labels: ⚙️ Setting

#88 perform(Security Context) - API 호출 시, 인증 객체가 DB를 조회하는 비효율적 인증 방식 개선
  src/main/java/org/com/dungeontalk/global/security/CustomUserDetails.java
  src/main/java/org/com/dungeontalk/global/security/JwtAuthenticationFilter.java
  src/main/java/org/com/dungeontalk/global/security/JwtProvider.java
  src/main/java/org/com/dungeontalk/global/security/JwtService.java
Labels: 🎤 Perform

#102 Chat, AiChat, Member, auth 쪽 테스트 코드 작성
  build.gradle
  src/test/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoomTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/repository/AiGameRoomRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/service/AiApiServiceTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/service/AiGameFlowServiceTest.java
  src/test/java/org/com/dungeontalk/domain/aichat/service/AiGameStateServiceTest.java
  src/test/java/org/com/dungeontalk/domain/auth/controller/AuthControllerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/controller/ValkeyControllerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/entity/AuthTest.java
  src/test/java/org/com/dungeontalk/domain/auth/manager/ActualLoginManagerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/manager/AuthRedisManagerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/manager/BruteForceManagerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/manager/CookieManagerTest.java
  src/test/java/org/com/dungeontalk/domain/auth/repository/AuthRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/auth/service/AuthServiceTest.java
  src/test/java/org/com/dungeontalk/domain/auth/service/ValkeyServiceTest.java
  src/test/java/org/com/dungeontalk/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/org/com/dungeontalk/domain/chat/controller/ChatRoomMemberControllerTest.java
  src/test/java/org/com/dungeontalk/domain/member/controller/MemberControllerTest.java
  src/test/java/org/com/dungeontalk/domain/member/repository/MemberRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/member/service/MemberServiceTest.java
  src/test/java/org/com/dungeontalk/global/support/TestJpaConfig.java
  src/test/java/org/com/dungeontalk/global/websocket/JwtHandshakeInterceptorTest.java
  src/test/java/org/com/dungeontalk/global/websocket/WebSocketDisconnectHandlerTest.java
  src/test/resources/application-test.properties
Labels: ✅ Test

#104 Feat/dgt-101
  src/main/java/org/com/dungeontalk/domain/gamecharacter/controller/GameCharacterController.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/dto/request/AddExperienceRequest.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/entity/RequestExp.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/repository/RequestExpRepository.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/service/GameCharacterService.java
  src/main/java/org/com/dungeontalk/domain/world/controller/WorldController.java
  src/main/java/org/com/dungeontalk/domain/world/dto/response/WorldResponse.java
  src/main/java/org/com/dungeontalk/domain/world/entity/World.java
  src/main/java/org/com/dungeontalk/domain/world/repository/WorldRepository.java
  src/main/java/org/com/dungeontalk/domain/world/service/WorldService.java
Labels: ✨ Feature

#107 버그 수정 - 채팅방 쪽 repository, service 테스트 실패 내용 확인
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatRoomMemberRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/org/com/dungeontalk/domain/chat/service/ChatMessageServiceTest.java
Labels: 🐞 Bugfix

#109 feat(Game System): 게임 종료 시스템 및 UI 개선 완료
  .claude/settings.local.json
  src/main/java/org/com/dungeontalk/domain/aichat/common/AiGameConstants.java
  src/main/java/org/com/dungeontalk/domain/aichat/common/AiMessageType.java
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiChatStompController.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGameMessageSendRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiGenerateRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/request/AiServiceRequest.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiServiceResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/entity/AiGameRoom.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiApiService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameFlowService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/controller/GameCharacterController.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/entity/GameCharacter.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/service/GameCharacterService.java
  src/main/java/org/com/dungeontalk/domain/matching/common/WorldType.java
  src/main/java/org/com/dungeontalk/domain/matching/config/MatchingStartupConfig.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingController.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingWebSocketController.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/request/MatchingJoinRequest.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/MatchingCompleteResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/MatchingStatusResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/QueueStatsResponse.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/response/WorldQueueInfo.java
  src/main/java/org/com/dungeontalk/domain/matching/dto/websocket/MatchingWebSocketMessage.java
  src/main/java/org/com/dungeontalk/domain/matching/factory/MatchingRoomFactory.java
  src/main/java/org/com/dungeontalk/domain/matching/factory/RoomCreationContext.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingQueueManager.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingService.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingWebSocketMessageFactory.java
  src/main/java/org/com/dungeontalk/domain/matching/service/MatchingWebSocketService.java
  src/main/java/org/com/dungeontalk/domain/matching/service/WorldTypeCompatService.java
  src/main/java/org/com/dungeontalk/domain/worldtype/config/WorldTypeDataInitializer.java
  src/main/java/org/com/dungeontalk/domain/worldtype/controller/WorldTypeController.java
  src/main/java/org/com/dungeontalk/domain/worldtype/dto/request/WorldTypeCreateRequest.java
  src/main/java/org/com/dungeontalk/domain/worldtype/dto/request/WorldTypeUpdateRequest.java
  src/main/java/org/com/dungeontalk/domain/worldtype/dto/response/WorldTypeResponse.java
  src/main/java/org/com/dungeontalk/domain/worldtype/entity/WorldType.java
  src/main/java/org/com/dungeontalk/domain/worldtype/repository/WorldTypeRepository.java
  src/main/java/org/com/dungeontalk/domain/worldtype/service/WorldTypeService.java
  src/main/java/org/com/dungeontalk/global/config/CorsConfig.java
  src/main/resources/db/migration/V2025_01_01__Create_WorldTypes_Table.sql
  src/main/resources/static/dungeon-game.html
  src/main/resources/static/worldtype-test.html
Labels: ✨ Feature

#113 [feat] AI 게임 종료 시 클리어 판별 및 경험치 지급 시스템 구현
  src/main/java/org/com/dungeontalk/domain/aichat/common/AiChatConstants.java
  src/main/java/org/com/dungeontalk/domain/aichat/dto/response/AiServiceResponse.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiApiService.java
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameFlowService.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/controller/GameCharacterController.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/dto/request/GameResultRequest.java
  src/main/java/org/com/dungeontalk/domain/gamecharacter/service/GameCharacterService.java
  src/main/java/org/com/dungeontalk/domain/room/dto/UnifiedMessageRequest.java
  src/main/java/org/com/dungeontalk/domain/world/dto/response/WorldResponse.java
  src/main/java/org/com/dungeontalk/domain/world/entity/World.java
  src/main/java/org/com/dungeontalk/global/config/AppConfig.java
  src/main/resources/static/dungeon-game.html
Labels: ✨ Feature

#117 cicd: dungeontalk ci-cd 구축 위한 properties 파일 작성
  src/main/resources/application-prod.properties
Labels: 🤖 CI/CD

#123 [fix] WebSocket 연결 끊김 관련 설정 확인 및 수정
  src/main/java/org/com/dungeontalk/domain/aichat/controller/AiChatStompController.java
  src/main/java/org/com/dungeontalk/domain/chat/controller/ChatStompController.java
  src/main/java/org/com/dungeontalk/domain/matching/controller/MatchingWebSocketController.java
  src/main/java/org/com/dungeontalk/domain/room/controller/UnifiedStompController.java
  src/main/resources/application-prod.properties
Labels: 🐞 Bugfix

#127 [fix] 님 뜨는 오류 수정
  src/main/java/org/com/dungeontalk/domain/aichat/service/AiGameMessageService.java
  src/main/resources/static/dungeon-game-styled.html
  src/main/resources/static/js/dungeon-game.js
Labels: 🚮 chore
